export const REPOSITORY = "https://github.com/wagerfield/nuxtflix"
export const WAGERFIELD = "https://github.com/wagerfield"
export const CONTENTFUL = "https://www.contentful.com"
export const NETLIFY = "https://www.netlify.com"
export const NUXT = "https://nuxtjs.org"
